# Generated by Django 4.0 on 2021-12-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(help_text='Max of 8 Characters', max_length=8, unique=True)),
                ('image', models.ImageField(upload_to='')),
                ('date_of_birth', models.DateField()),
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
            ],
        ),
    ]
